-- TSO Edu စာစီစကုံး (composition) topic bank: 100 curated Myanmar essay
-- titles across 10 categories with a beginner/intermediate/advanced
-- difficulty tag. This is a topic picker/bank only — it is intentionally
-- separate from the app's local generation_topic_knowledge table (SQLite),
-- which grounds အဆိုအခြဲ (debate) and English essay generation with
-- angles/benefits/risks/examples. Do not merge the two: different content,
-- different purpose.
--
-- Mirrors the bundled SQLite copy at
-- backend/edu_app/data/essay_topics_100.csv, loaded into SQLite by
-- backend/edu_app/build_generation_database.py. This Postgres/Supabase
-- table exists so the same topic bank is available for any admin/creator
-- tooling or future sync built against the live database.
-- Safe to re-run: ON CONFLICT (title) DO NOTHING.
CREATE TABLE IF NOT EXISTS essay_topics (
  id SERIAL PRIMARY KEY,
  title TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  keywords TEXT[] NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_essay_topics_category ON essay_topics(category);
CREATE INDEX IF NOT EXISTS idx_essay_topics_difficulty ON essay_topics(difficulty);

insert into essay_topics(title,category,difficulty,keywords) values
('ပညာ၏တန်ဖိုး','ပညာရေး','beginner',ARRAY['ပညာ၏တန်ဖိုး']),
('ဆရာကျေးဇူး','ပညာရေး','beginner',ARRAY['ဆရာကျေးဇူး']),
('စာဖတ်ခြင်း၏အကျိုးကျေးဇူး','ပညာရေး','beginner',ARRAY['စာဖတ်ခြင်း၏အကျိုးကျေးဇူး']),
('စာကြည့်တိုက်၏အရေးပါမှု','ပညာရေး','intermediate',ARRAY['စာကြည့်တိုက်၏အရေးပါမှု']),
('တက္ကသိုလ်ဘဝ','ပညာရေး','intermediate',ARRAY['တက္ကသိုလ်ဘဝ']),
('ကိုယ်တိုင်လေ့လာခြင်း','ပညာရေး','intermediate',ARRAY['ကိုယ်တိုင်လေ့လာခြင်း']),
('အွန်လိုင်းပညာရေး','ပညာရေး','intermediate',ARRAY['အွန်လိုင်းပညာရေး']),
('စာမေးပွဲပြင်ဆင်နည်း','ပညာရေး','advanced',ARRAY['စာမေးပွဲပြင်ဆင်နည်း']),
('ကျောင်းစည်းကမ်း','ပညာရေး','advanced',ARRAY['ကျောင်းစည်းကမ်း']),
('အသက်မွေးဝမ်းကျောင်းပညာ','ပညာရေး','advanced',ARRAY['အသက်မွေးဝမ်းကျောင်းပညာ']),
('အချိန်၏တန်ဖိုး','ကိုယ်ကျင့်တရား','beginner',ARRAY['အချိန်၏တန်ဖိုး']),
('ရိုးသားခြင်း','ကိုယ်ကျင့်တရား','beginner',ARRAY['ရိုးသားခြင်း']),
('ကြိုးစားခြင်း','ကိုယ်ကျင့်တရား','beginner',ARRAY['ကြိုးစားခြင်း']),
('စည်းကမ်း','ကိုယ်ကျင့်တရား','intermediate',ARRAY['စည်းကမ်း']),
('တာဝန်ယူမှု','ကိုယ်ကျင့်တရား','intermediate',ARRAY['တာဝန်ယူမှု']),
('သည်းခံခြင်း','ကိုယ်ကျင့်တရား','intermediate',ARRAY['သည်းခံခြင်း']),
('ဇွဲလုံ့လ','ကိုယ်ကျင့်တရား','intermediate',ARRAY['ဇွဲလုံ့လ']),
('မေတ္တာ','ကိုယ်ကျင့်တရား','advanced',ARRAY['မေတ္တာ']),
('ခွင့်လွှတ်ခြင်း','ကိုယ်ကျင့်တရား','advanced',ARRAY['ခွင့်လွှတ်ခြင်း']),
('ကတိတည်ခြင်း','ကိုယ်ကျင့်တရား','advanced',ARRAY['ကတိတည်ခြင်း']),
('မိဘကျေးဇူး','မိသားစု','beginner',ARRAY['မိဘကျေးဇူး']),
('မောင်နှမချစ်ခင်မှု','မိသားစု','beginner',ARRAY['မောင်နှမချစ်ခင်မှု']),
('အဖိုးအဖွား၏အခန်းကဏ္ဍ','မိသားစု','beginner',ARRAY['အဖိုးအဖွား၏အခန်းကဏ္ဍ']),
('မိသားစုစည်းလုံးမှု','မိသားစု','intermediate',ARRAY['မိသားစုစည်းလုံးမှု']),
('အိမ်တွင်းပညာပေး','မိသားစု','intermediate',ARRAY['အိမ်တွင်းပညာပေး']),
('မိသားစုနှင့်ပျော်ရွှင်မှု','မိသားစု','intermediate',ARRAY['မိသားစုနှင့်ပျော်ရွှင်မှု']),
('ကလေးပြုစုပျိုးထောင်ရေး','မိသားစု','intermediate',ARRAY['ကလေးပြုစုပျိုးထောင်ရေး']),
('မိသားစုတာဝန်','မိသားစု','advanced',ARRAY['မိသားစုတာဝန်']),
('မေတ္တာနှောင်ကြိုး','မိသားစု','advanced',ARRAY['မေတ္တာနှောင်ကြိုး']),
('မိသားစုတန်ဖိုး','မိသားစု','advanced',ARRAY['မိသားစုတန်ဖိုး']),
('စည်းလုံးညီညွတ်ခြင်း','လူမှုရေး','beginner',ARRAY['စည်းလုံးညီညွတ်ခြင်း']),
('အကူအညီပေးခြင်း','လူမှုရေး','beginner',ARRAY['အကူအညီပေးခြင်း']),
('စေတနာ့ဝန်ထမ်းလုပ်ငန်း','လူမှုရေး','beginner',ARRAY['စေတနာ့ဝန်ထမ်းလုပ်ငန်း']),
('လူမှုကွန်ရက်','လူမှုရေး','intermediate',ARRAY['လူမှုကွန်ရက်']),
('ယဉ်ကျေးပျူငှာမှု','လူမှုရေး','intermediate',ARRAY['ယဉ်ကျေးပျူငှာမှု']),
('အများပိုင်ပစ္စည်းထိန်းသိမ်းရေး','လူမှုရေး','intermediate',ARRAY['အများပိုင်ပစ္စည်းထိန်းသိမ်းရေး']),
('လူငယ်နှင့်လူမှုရေး','လူမှုရေး','intermediate',ARRAY['လူငယ်နှင့်လူမှုရေး']),
('နိုင်ငံသားတာဝန်','လူမှုရေး','advanced',ARRAY['နိုင်ငံသားတာဝန်']),
('အသိုင်းအဝိုင်းဖွံ့ဖြိုးရေး','လူမှုရေး','advanced',ARRAY['အသိုင်းအဝိုင်းဖွံ့ဖြိုးရေး']),
('ငြိမ်းချမ်းစွာနေထိုင်ခြင်း','လူမှုရေး','advanced',ARRAY['ငြိမ်းချမ်းစွာနေထိုင်ခြင်း']),
('သဘာဝပတ်ဝန်းကျင်ထိန်းသိမ်းရေး','ပတ်ဝန်းကျင်','beginner',ARRAY['သဘာဝပတ်ဝန်းကျင်ထိန်းသိမ်းရေး']),
('သစ်ပင်စိုက်ပျိုးခြင်း','ပတ်ဝန်းကျင်','beginner',ARRAY['သစ်ပင်စိုက်ပျိုးခြင်း']),
('ရေထိန်းသိမ်းရေး','ပတ်ဝန်းကျင်','beginner',ARRAY['ရေထိန်းသိမ်းရေး']),
('လေထုညစ်ညမ်းမှု','ပတ်ဝန်းကျင်','intermediate',ARRAY['လေထုညစ်ညမ်းမှု']),
('အမှိုက်လျှော့ချရေး','ပတ်ဝန်းကျင်','intermediate',ARRAY['အမှိုက်လျှော့ချရေး']),
('ပြန်လည်အသုံးပြုခြင်း','ပတ်ဝန်းကျင်','intermediate',ARRAY['ပြန်လည်အသုံးပြုခြင်း']),
('တောရိုင်းတိရစ္ဆာန်ကာကွယ်ရေး','ပတ်ဝန်းကျင်','intermediate',ARRAY['တောရိုင်းတိရစ္ဆာန်ကာကွယ်ရေး']),
('ရာသီဥတုပြောင်းလဲမှု','ပတ်ဝန်းကျင်','advanced',ARRAY['ရာသီဥတုပြောင်းလဲမှု']),
('သဘာဝဘေးအန္တရာယ်','ပတ်ဝန်းကျင်','advanced',ARRAY['သဘာဝဘေးအန္တရာယ်']),
('မြစ်နှင့်ချောင်းများထိန်းသိမ်းရေး','ပတ်ဝန်းကျင်','advanced',ARRAY['မြစ်နှင့်ချောင်းများထိန်းသိမ်းရေး']),
('အားကစား၏အကျိုးကျေးဇူး','ကျန်းမာရေး','beginner',ARRAY['အားကစား၏အကျိုးကျေးဇူး']),
('ကျန်းမာသောအစားအစာ','ကျန်းမာရေး','beginner',ARRAY['ကျန်းမာသောအစားအစာ']),
('သန့်ရှင်းရေး','ကျန်းမာရေး','beginner',ARRAY['သန့်ရှင်းရေး']),
('အိပ်စက်ခြင်း၏အရေးပါမှု','ကျန်းမာရေး','intermediate',ARRAY['အိပ်စက်ခြင်း၏အရေးပါမှု']),
('စိတ်ကျန်းမာရေး','ကျန်းမာရေး','intermediate',ARRAY['စိတ်ကျန်းမာရေး']),
('ရေသောက်ခြင်း','ကျန်းမာရေး','intermediate',ARRAY['ရေသောက်ခြင်း']),
('ကာယလေ့ကျင့်ခန်း','ကျန်းမာရေး','intermediate',ARRAY['ကာယလေ့ကျင့်ခန်း']),
('ရောဂါကာကွယ်ရေး','ကျန်းမာရေး','advanced',ARRAY['ရောဂါကာကွယ်ရေး']),
('ဆေးလိပ်၏ဆိုးကျိုး','ကျန်းမာရေး','advanced',ARRAY['ဆေးလိပ်၏ဆိုးကျိုး']),
('အရက်၏ဆိုးကျိုး','ကျန်းမာရေး','advanced',ARRAY['အရက်၏ဆိုးကျိုး']),
('နည်းပညာနှင့်လူငယ်များ','နည်းပညာ','beginner',ARRAY['နည်းပညာနှင့်လူငယ်များ']),
('Artificial Intelligence','နည်းပညာ','beginner',ARRAY['Artificial','Intelligence']),
('အင်တာနက်အသုံးပြုမှု','နည်းပညာ','beginner',ARRAY['အင်တာနက်အသုံးပြုမှု']),
('ဆိုရှယ်မီဒီယာ','နည်းပညာ','intermediate',ARRAY['ဆိုရှယ်မီဒီယာ']),
('ဒစ်ဂျစ်တယ်လုံခြုံရေး','နည်းပညာ','intermediate',ARRAY['ဒစ်ဂျစ်တယ်လုံခြုံရေး']),
('မိုဘိုင်းဖုန်း','နည်းပညာ','intermediate',ARRAY['မိုဘိုင်းဖုန်း']),
('အွန်လိုင်းစျေးဝယ်','နည်းပညာ','intermediate',ARRAY['အွန်လိုင်းစျေးဝယ်']),
('Cloud နည်းပညာ','နည်းပညာ','advanced',ARRAY['Cloud','နည်းပညာ']),
('စက်ရုပ်နည်းပညာ','နည်းပညာ','advanced',ARRAY['စက်ရုပ်နည်းပညာ']),
('အနာဂတ်နည်းပညာ','နည်းပညာ','advanced',ARRAY['အနာဂတ်နည်းပညာ']),
('မြန်မာ့ယဉ်ကျေးမှု','ယဉ်ကျေးမှု','beginner',ARRAY['မြန်မာ့ယဉ်ကျေးမှု']),
('ရိုးရာပွဲတော်များ','ယဉ်ကျေးမှု','beginner',ARRAY['ရိုးရာပွဲတော်များ']),
('သီတင်းကျွတ်','ယဉ်ကျေးမှု','beginner',ARRAY['သီတင်းကျွတ်']),
('တန်ဆောင်တိုင်','ယဉ်ကျေးမှု','intermediate',ARRAY['တန်ဆောင်တိုင်']),
('Thingyan','ယဉ်ကျေးမှု','intermediate',ARRAY['Thingyan']),
('ရိုးရာအစားအစာ','ယဉ်ကျေးမှု','intermediate',ARRAY['ရိုးရာအစားအစာ']),
('ရိုးရာအဝတ်အစား','ယဉ်ကျေးမှု','intermediate',ARRAY['ရိုးရာအဝတ်အစား']),
('ဘာသာစကားတန်ဖိုး','ယဉ်ကျေးမှု','advanced',ARRAY['ဘာသာစကားတန်ဖိုး']),
('အနုပညာ','ယဉ်ကျေးမှု','advanced',ARRAY['အနုပညာ']),
('ဂီတ','ယဉ်ကျေးမှု','advanced',ARRAY['ဂီတ']),
('ငွေစုခြင်း','စီးပွားရေး','beginner',ARRAY['ငွေစုခြင်း']),
('စွန့်ဦးတီထွင်မှု','စီးပွားရေး','beginner',ARRAY['စွန့်ဦးတီထွင်မှု']),
('အသေးစားစီးပွားရေး','စီးပွားရေး','beginner',ARRAY['အသေးစားစီးပွားရေး']),
('အလုပ်အကိုင်','စီးပွားရေး','intermediate',ARRAY['အလုပ်အကိုင်']),
('ဖောက်သည်ဝန်ဆောင်မှု','စီးပွားရေး','intermediate',ARRAY['ဖောက်သည်ဝန်ဆောင်မှု']),
('ငွေကြေးစီမံခန့်ခွဲမှု','စီးပွားရေး','intermediate',ARRAY['ငွေကြေးစီမံခန့်ခွဲမှု']),
('ဈေးကွက်','စီးပွားရေး','intermediate',ARRAY['ဈေးကွက်']),
('ကုန်သွယ်ရေး','စီးပွားရေး','advanced',ARRAY['ကုန်သွယ်ရေး']),
('လုပ်ငန်းကျင့်ဝတ်','စီးပွားရေး','advanced',ARRAY['လုပ်ငန်းကျင့်ဝတ်']),
('အောင်မြင်သောစီးပွားရေး','စီးပွားရေး','advanced',ARRAY['အောင်မြင်သောစီးပွားရေး']),
('ခရီးသွားခြင်း','ခရီးသွား','beginner',ARRAY['ခရီးသွားခြင်း']),
('ပုဂံ','ခရီးသွား','beginner',ARRAY['ပုဂံ']),
('အင်းလေးကန်','ခရီးသွား','beginner',ARRAY['အင်းလေးကန်']),
('ငပလီကမ်းခြေ','ခရီးသွား','intermediate',ARRAY['ငပလီကမ်းခြေ']),
('တောင်ကြီး','ခရီးသွား','intermediate',ARRAY['တောင်ကြီး']),
('မန္တလေး','ခရီးသွား','intermediate',ARRAY['မန္တလေး']),
('ရန်ကုန်','ခရီးသွား','intermediate',ARRAY['ရန်ကုန်']),
('သဘာဝခရီးသွား','ခရီးသွား','advanced',ARRAY['သဘာဝခရီးသွား']),
('ယဉ်ကျေးမှုခရီးသွား','ခရီးသွား','advanced',ARRAY['ယဉ်ကျေးမှုခရီးသွား']),
('လုံခြုံသောခရီးသွားခြင်း','ခရီးသွား','advanced',ARRAY['လုံခြုံသောခရီးသွားခြင်း'])
ON CONFLICT (title) DO NOTHING;
